/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products */
        get: operations["listProducts"];
        put?: never;
        /** Create a product */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders */
        get: operations["listOrders"];
        put?: never;
        /** Create an order */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an order */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details. */
        Problem: {
            /**
             * Format: uri
             * @default about:blank
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
        };
        /** @enum {string} */
        OrderStatus: "pending" | "confirmed" | "fulfilled" | "cancelled";
        /** @enum {string} */
        Unit: "kg" | "pcs" | "liter";
        Product: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            supplier_id: string;
            sku: string;
            name: string;
            name_ms?: string | null;
            category: string;
            unit: components["schemas"]["Unit"];
            halal_certified: boolean;
            description?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ProductCreate: {
            /** Format: uuid */
            supplier_id: string;
            sku: string;
            name: string;
            name_ms?: string;
            category: string;
            unit: components["schemas"]["Unit"];
            /** @default false */
            halal_certified: boolean;
            description?: string;
        };
        ProductPage: {
            data: components["schemas"]["Product"][];
            next_cursor?: string | null;
        };
        OrderItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            product_id: string;
            quantity: number;
            unit_price_cents: number;
            line_total_cents: number;
        };
        OrderItemCreate: {
            /** Format: uuid */
            product_id: string;
            quantity: number;
        };
        Order: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            restaurant_id: string;
            /** Format: uuid */
            supplier_id: string;
            status: components["schemas"]["OrderStatus"];
            /** Format: date */
            delivery_date: string;
            delivery_window?: string | null;
            total_amount_cents: number;
            items: components["schemas"]["OrderItem"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OrderCreate: {
            /** Format: uuid */
            restaurant_id: string;
            /** Format: uuid */
            supplier_id: string;
            /** Format: date */
            delivery_date: string;
            delivery_window?: string;
            items: components["schemas"]["OrderItemCreate"][];
        };
        OrderPage: {
            data: components["schemas"]["Order"][];
            next_cursor?: string | null;
        };
    };
    responses: {
        /** @description The request was malformed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Conflict (e.g., idempotency key reused with a different body). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /**
         * @description A client-generated unique key (UUID recommended) that makes this
         *     request safe to retry. The server stores the result keyed by this
         *     value; replays with the same key return the original response.
         */
        IdempotencyKey: string;
        /** @description Opaque cursor returned in the previous page's `next_cursor`. */
        CursorParam: string;
        LimitParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProducts: {
        parameters: {
            query?: {
                /** @description Opaque cursor returned in the previous page's `next_cursor`. */
                cursor?: components["parameters"]["CursorParam"];
                limit?: components["parameters"]["LimitParam"];
                supplier_id?: string;
                category?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of products. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description A client-generated unique key (UUID recommended) that makes this
                 *     request safe to retry. The server stores the result keyed by this
                 *     value; replays with the same key return the original response.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Product created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    listOrders: {
        parameters: {
            query?: {
                /** @description Opaque cursor returned in the previous page's `next_cursor`. */
                cursor?: components["parameters"]["CursorParam"];
                limit?: components["parameters"]["LimitParam"];
                status?: components["schemas"]["OrderStatus"];
                supplier_id?: string;
                restaurant_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of orders. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description A client-generated unique key (UUID recommended) that makes this
                 *     request safe to retry. The server stores the result keyed by this
                 *     value; replays with the same key return the original response.
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Order created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
